version: "3"
services:
  nginx:
    image: nginx:1.21-alpine
    container_name: static-nginx
    hostname: nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src:/usr/share/nginx/html
    restart: always
